name: 'stripe_payment_analysis'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  stripe_payment_analysis:
    Payments:
      +materialized: view
      staging:
        +materialized: view
        +schema: stg_payments
      denormalized:
        +materialized: table
        +schema: payments_enhanced
      reporting:
        +materialized: table
        +schema: payments_metrics